// libs/react/examples/accordion/disabled.tsx
import { Accordion } from "@ark-ui/react/accordion";

export const Disabled = () => {
  const items = ["panel-1", "panel-2", "panel-3"];
  return (
    <Accordion.Root>
      {items.map((item) => (
        <Accordion.Item key={item} value={item} disabled={item === "panel-2"}>
          <Accordion.ItemTrigger>{item} trigger</Accordion.ItemTrigger>
          <Accordion.ItemContent>{item} content</Accordion.ItemContent>
        </Accordion.Item>
      ))}
    </Accordion.Root>
  );
};

// libs/solid/examples/accordion/disabled.tsx
import { Accordion } from "@ark-ui/solid/accordion";
import { Index } from "solid-js";

export const Disabled = () => {
  const items = ["panel-1", "panel-2", "panel-3"];
  return (
    <Accordion.Root>
      <Index each={items}>
        {(item) => (
          <Accordion.Item value={item()} disabled={item() === "panel-2"}>
            <Accordion.ItemTrigger>{item()} trigger</Accordion.ItemTrigger>
            <Accordion.ItemContent>{item()} content</Accordion.ItemContent>
          </Accordion.Item>
        )}
      </Index>
    </Accordion.Root>
  );
};
