// playground/solid/src/listbox/index.tsx
import { createListCollection, Listbox } from "@ark-ui/solid/listbox";
import { Index } from "solid-js";

export const Basic = () => {
  const collection = createListCollection({ items: ["React", "Solid", "Vue"] });

  return (
    <Listbox.Root collection={collection}>
      <Listbox.Label>Select your Framework</Listbox.Label>
      <Listbox.Content>
        <Index each={collection.items}>
          {(item) => (
            <Listbox.Item item={item()}>
              <Listbox.ItemText>{item()}</Listbox.ItemText>
              <Listbox.ItemIndicator />
            </Listbox.Item>
          )}
        </Index>
      </Listbox.Content>
    </Listbox.Root>
  );
};

// playground/react/src/ark-ui/listbox/index.tsx
import { Listbox, createListCollection } from "@ark-ui/react/listbox";

export const Basic = () => {
  const collection = createListCollection({ items: ["React", "Solid", "Vue"] });

  return (
    <Listbox.Root collection={collection}>
      <Listbox.Label>Select your Framework</Listbox.Label>
      <Listbox.Content>
        {collection.items.map((item) => (
          <Listbox.Item key={item} item={item}>
            <Listbox.ItemText>{item}</Listbox.ItemText>
            <Listbox.ItemIndicator />
          </Listbox.Item>
        ))}
      </Listbox.Content>
    </Listbox.Root>
  );
};
