// examples/vue/src/checkbox/with-field.vue
<script setup lang="ts">
import { Checkbox } from "@ark-ui/vue/checkbox";
import { Field } from "@ark-ui/vue/field";
import { Check } from "lucide-vue-next";
</script>

<template>
  <Field.Root>
    <Checkbox.Root>
      <Checkbox.Label>Label</Checkbox.Label>
      <Checkbox.Control>
        <Checkbox.Indicator>
          <Check />
        </Checkbox.Indicator>
        <Checkbox.Indicator indeterminate>
          <MinusIcon />
        </Checkbox.Indicator>
      </Checkbox.Control>
      <Checkbox.HiddenInput />
    </Checkbox.Root>
    <Field.HelperText>Additional Info</Field.HelperText>
    <Field.ErrorText>Error Info</Field.ErrorText>
  </Field.Root>
</template>

// examples/react/src/checkbox/with-field.tsx
import { Checkbox } from "@ark-ui/react/checkbox";
import { Field } from "@ark-ui/react/field";
import { minimal, park, shadcn } from "@spark-css/themes";
import { clsx } from "clsx";
import { CheckIcon, MinusIcon } from "lucide-react";
import { type Theme, getTheme } from "../utils";

export const WithField = (props: Field.RootProps & { theme: Theme }) => {
  const checkbox = getTheme({ minimal: minimal.checkbox, park: park.checkbox, shadcn: shadcn.checkbox }, props.theme);
  const field = getTheme({ minimal: minimal.field, park: park.field, shadcn: shadcn.field }, props.theme);

  return (
    <Field.Root {...props} className={clsx(field.root)}>
      <Checkbox.Root className={clsx(checkbox.root)}>
        <Checkbox.Label className={clsx(checkbox.label)}>Label</Checkbox.Label>
        <Checkbox.Control className={clsx(checkbox.control)}>
          <Checkbox.Indicator className={clsx(checkbox.indicator)}>
            <CheckIcon />
          </Checkbox.Indicator>
          <Checkbox.Indicator indeterminate className={clsx(checkbox.indicator)}>
            <MinusIcon />
          </Checkbox.Indicator>
        </Checkbox.Control>
        <Checkbox.HiddenInput />
      </Checkbox.Root>
      <Field.HelperText className={clsx(field.helperText)}>Additional Info</Field.HelperText>
      <Field.ErrorText className={clsx(field.errorText)}>Error Info</Field.ErrorText>
    </Field.Root>
  );
};
