// examples/vue/src/avatar/closed.vue
<script setup lang="ts">
import { useForwardPropsEmits } from "@ark-ui/vue";
import {
  Avatar,
  type AvatarRootEmits,
  type AvatarRootProps,
} from "@ark-ui/vue/avatar";
import { computed } from "vue";

export interface AvatarProps extends AvatarRootProps {
  src?: string;
  name: string;
}

const props = defineProps<AvatarProps>();
const emits = defineEmits<AvatarRootEmits>();

const forwarded = useForwardPropsEmits(props, emits);

const getInitials = computed(() =>
  props.name
    .split(" ")
    .map((part) => part[0])
    .slice(0, 2)
    .join("")
    .toUpperCase()
);
</script>

<template>
  <Avatar.Root v-bind="forwarded">
    <Avatar.Fallback>{{ getInitials }}</Avatar.Fallback>
    <Avatar.Image v-if="props.src" :src="props.src" :alt="props.name" />
  </Avatar.Root>
</template>

// libs/react/examples/avatar/closed.tsx
import { Avatar as ArkAvatar } from "@ark-ui/react/avatar";
import { UserIcon } from "lucide-react";
import { forwardRef } from "react";

export interface AvatarProps extends ArkAvatar.RootProps {
  name?: string;
  src?: string;
}

export const Avatar = forwardRef<HTMLDivElement, AvatarProps>((props, ref) => {
  const { name, src, ...rootProps } = props;
  return (
    <ArkAvatar.Root ref={ref} {...rootProps}>
      <ArkAvatar.Fallback>{getInitials(name) || <UserIcon />}</ArkAvatar.Fallback>
      <ArkAvatar.Image src={src} alt={name} />
    </ArkAvatar.Root>
  );
});

const getInitials = (name = "") =>
  name
    .split(" ")
    .map((part) => part[0])
    .slice(0, 2)
    .join("")
    .toUpperCase();
