// playground/react/src/base-ui/separator/index.tsx
import { Separator } from "@base-ui-components/react/separator";

export const Basic = () => {
  return (
    <div>
      <a href="#placeholder">Home</a>
      <a href="#placeholder">Pricing</a>
      <a href="#placeholder">Blog</a>
      <a href="#placeholder">Support</a>

      <Separator orientation="vertical" />

      <a href="#placeholder">Log in</a>
      <a href="#placeholder">Sign up</a>
    </div>
  );
};

// playground/svelte/src/lib/bits-ui/separator/index.svelte
<script lang="ts">
import { Separator } from "bits-ui";
</script>

<div>
  <div>
    <h4>Bits UI</h4>
    <p>
      Headless UI components for Svelte.
    </p>
  </div>
  <Separator.Root
   
  />
  <div>
    <div>Blog</div>
    <Separator.Root
      orientation="vertical"
     
    />
    <div>Docs</div>
    <Separator.Root
      orientation="vertical"
     
    />
    <div>Source</div>
  </div>
</div>
