// playground/vue/src/ark-ui/toast/index.vue
<script setup lang="ts">
import { Toast, Toaster, createToaster } from "@ark-ui/vue/toast";

const toaster = createToaster({
  placement: "bottom-end",
  overlap: true,
  gap: 24
});

const createToast = () => {
  toaster.create({
    title: "Title",
    description: "Description",
    type: "info"
  });
};
</script>

<template>
  <button @click="createToast">Create Toast</button>
  <Toaster :toaster="toaster" v-slot="toast">
    <Toast.Root>
      <Toast.Title>{{ toast.title }}</Toast.Title>
      <Toast.Description>{{ toast.description }}</Toast.Description>
      <Toast.ActionTrigger>Action</Toast.ActionTrigger>
      <Toast.CloseTrigger>Close</Toast.CloseTrigger>
    </Toast.Root>
  </Toaster>
</template>

// playground/solid/src/ark-ui/toast/index.tsx
import { Toast, Toaster, createToaster } from "@ark-ui/solid/toast";
import { XIcon } from "lucide-solid";

export const Basic = () => {
  const toaster = createToaster({
    placement: "bottom-end",
    gap: 24
  });

  return (
    <div>
      <button
        type="button"
        onClick={() =>
          toaster.create({
            title: "Loading!",
            description: "We are loading something for you. Please wait.",
            type: "info"
          })
        }
      >
        Add Toast
      </button>
      <Toaster toaster={toaster}>
        {(toast) => (
          <Toast.Root>
            <Toast.Title>{toast().title}</Toast.Title>
            <Toast.Description>{toast().description}</Toast.Description>
            <Toast.CloseTrigger>
              <XIcon />
            </Toast.CloseTrigger>
          </Toast.Root>
        )}
      </Toaster>
    </div>
  );
};
