// playground/solid/src/toggle-group/index.tsx
import { ToggleGroup } from "@ark-ui/solid/toggle-group";

export const Basic = () => {
  return (
    <ToggleGroup.Root>
      <ToggleGroup.Item value="a">A</ToggleGroup.Item>
      <ToggleGroup.Item value="b">B</ToggleGroup.Item>
      <ToggleGroup.Item value="c">C</ToggleGroup.Item>
    </ToggleGroup.Root>
  );
};

// playground/vue/src/ark-ui/toggle-group/index.vue
<script setup lang="ts">
import { ToggleGroup } from "@ark-ui/vue/toggle-group";
</script>

<template>
  <ToggleGroup.Root>
    <ToggleGroup.Item value="a">A</ToggleGroup.Item>
    <ToggleGroup.Item value="b">B</ToggleGroup.Item>
    <ToggleGroup.Item value="c">C</ToggleGroup.Item>
  </ToggleGroup.Root>
</template>
