// libs/react/examples/segment-group/disabled.tsx
import { SegmentGroup } from "@ark-ui/react/segment-group";

export const Disabled = () => {
  const frameworks = ["React", "Solid", "Svelte", "Vue"];
  return (
    <SegmentGroup.Root defaultValue="React">
      <SegmentGroup.Indicator />
      {frameworks.map((framework) => (
        <SegmentGroup.Item key={framework} value={framework} disabled={framework === "Svelte"}>
          <SegmentGroup.ItemText>{framework}</SegmentGroup.ItemText>
          <SegmentGroup.ItemControl />
          <SegmentGroup.ItemHiddenInput />
        </SegmentGroup.Item>
      ))}
    </SegmentGroup.Root>
  );
};

// libs/solid/examples/segment-group/disabled.tsx
import { SegmentGroup } from "@ark-ui/solid/segment-group";
import { Index } from "solid-js";

export const Disabled = () => {
  const frameworks = ["React", "Solid", "Svelte", "Vue"];
  return (
    <SegmentGroup.Root value={"React"}>
      <SegmentGroup.Indicator />
      <Index each={frameworks}>
        {(framework) => (
          <SegmentGroup.Item value={framework()} disabled={framework() === "Svelte"}>
            <SegmentGroup.ItemText>{framework()}</SegmentGroup.ItemText>
            <SegmentGroup.ItemControl />
            <SegmentGroup.ItemHiddenInput />
          </SegmentGroup.Item>
        )}
      </Index>
    </SegmentGroup.Root>
  );
};
