// playground/vue/src/radio-group/index.vue
<script setup lang="ts">
import { RadioGroup } from "@ark-ui/vue/radio-group";
import { ref } from "vue";

const frameworks = ref(["React", "Solid", "Vue"]);
</script>

<template>
  <RadioGroup.Root>
    <RadioGroup.Label>Framework</RadioGroup.Label>
    <RadioGroup.Indicator />
    <RadioGroup.Item v-for="framework in frameworks" :key="framework" :value="framework">
      <RadioGroup.ItemText>{{ framework }}</RadioGroup.ItemText>
      <RadioGroup.ItemControl />
      <RadioGroup.ItemHiddenInput />
    </RadioGroup.Item>
  </RadioGroup.Root>
</template>

// playground/react/src/radix-ui/radio-group/index.tsx
import { Label } from "@radix-ui/react-label";
import * as RadioGroup from "@radix-ui/react-radio-group";

export const Basic = () => (
  <Label>
    Favourite pet
    <RadioGroup.Root defaultValue="1">
      <Label>
        <RadioGroup.Item value="1">
          <RadioGroup.Indicator />
        </RadioGroup.Item>
        Cat
      </Label>{" "}
      <Label>
        <RadioGroup.Item value="2">
          <RadioGroup.Indicator />
        </RadioGroup.Item>
        Dog
      </Label>{" "}
      <Label>
        <RadioGroup.Item value="3">
          <RadioGroup.Indicator />
        </RadioGroup.Item>
        Rabbit
      </Label>
    </RadioGroup.Root>
  </Label>
);
