// examples/solid/src/accordion/multiple.tsx
import { Accordion } from "@ark-ui/solid/accordion";
import { ChevronDownIcon } from "lucide-solid";
import { Index } from "solid-js";

export const Multiple = () => {
  return (
    <Accordion.Root value={["React"]} multiple>
      <Index each={["React", "Solid", "Vue"]}>
        {(item) => (
          <Accordion.Item value={item()}>
            <Accordion.ItemTrigger>
              What is {item()}?
              <Accordion.ItemIndicator>
                <ChevronDownIcon />
              </Accordion.ItemIndicator>
            </Accordion.ItemTrigger>
            <Accordion.ItemContent>
              {item()} is a JavaScript library for building user interfaces.
            </Accordion.ItemContent>
          </Accordion.Item>
        )}
      </Index>
    </Accordion.Root>
  );
};

// examples/vue/src/accordion/multiple.vue
<script setup lang="ts">
import { Accordion } from "@ark-ui/vue/accordion";
import { ChevronDown } from "lucide-vue-next";
import { ref } from "vue";

const items = ref(["React", "Solid", "Vue"]);
</script>

<template>
  <Accordion.Root multiple>
    <Accordion.Item v-for="item in items" :key="item" :value="item">
      <Accordion.ItemTrigger>
        What is {{ item }}?
        <Accordion.ItemIndicator><ChevronDown /></Accordion.ItemIndicator>
      </Accordion.ItemTrigger>
      <Accordion.ItemContent
        >{{ item }} is a JavaScript library for building user
        interfaces.</Accordion.ItemContent
      >
    </Accordion.Item>
  </Accordion.Root>
</template>
