// examples/solid/src/toggle-group/initial-value.tsx
import { ToggleGroup } from "@ark-ui/solid/toggle-group";

export const InitialValue = () => {
  return (
    <ToggleGroup.Root value={["b"]}>
      <ToggleGroup.Item value="a">A</ToggleGroup.Item>
      <ToggleGroup.Item value="b">B</ToggleGroup.Item>
      <ToggleGroup.Item value="c">C</ToggleGroup.Item>
    </ToggleGroup.Root>
  );
};

// examples/solid/src/radio-group/initial-value.tsx
import { RadioGroup } from "@ark-ui/solid/radio-group";
import { Index } from "solid-js";

export const InitialValue = () => {
  const frameworks = ["React", "Solid", "Vue"];

  return (
    <RadioGroup.Root value="Solid">
      <RadioGroup.Label>Framework</RadioGroup.Label>
      <Index each={frameworks}>
        {(framework) => (
          <RadioGroup.Item value={framework()}>
            <RadioGroup.ItemText>{framework()}</RadioGroup.ItemText>
            <RadioGroup.ItemControl />
            <RadioGroup.ItemHiddenInput />
          </RadioGroup.Item>
        )}
      </Index>
    </RadioGroup.Root>
  );
};
