// examples/react/src/select/form-library.tsx
import { Select, createListCollection } from "@ark-ui/react/select";
import { minimal, park, shadcn } from "@spark-css/themes";
import { clsx } from "clsx";
import { ChevronDownIcon } from "lucide-react";
import { type SubmitHandler, useForm } from "react-hook-form";
import { type Theme, getTheme } from "../utils";

interface Inputs {
  framework: string;
}

export const FormLibrary = ({ theme }: { theme: Theme }) => {
  const styledSlots = getTheme({ minimal: minimal.select, park: park.select, shadcn: shadcn.select }, theme);
  const collection = createListCollection({ items: ["React", "Solid", "Vue"] });
  const { register, handleSubmit } = useForm<Inputs>();

  const onSubmit: SubmitHandler<Inputs> = (data) => window.alert(JSON.stringify(data));

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <Select.Root collection={collection}>
        <Select.Label>Framework</Select.Label>
        <Select.HiddenSelect {...register("framework")} />
        <Select.Control>
          <Select.Trigger>
            <Select.ValueText placeholder="Select a Framework" />
            <Select.Indicator>
              <ChevronDownIcon />
            </Select.Indicator>
          </Select.Trigger>
          <Select.ClearTrigger>Clear</Select.ClearTrigger>
        </Select.Control>
        <Select.Positioner>
          <Select.Content>
            <Select.ItemGroup>
              <Select.ItemGroupLabel>Frameworks</Select.ItemGroupLabel>
              {collection.items.map((item) => (
                <Select.Item key={item} item={item}>
                  <Select.ItemText>{item}</Select.ItemText>
                  <Select.ItemIndicator>✓</Select.ItemIndicator>
                </Select.Item>
              ))}
            </Select.ItemGroup>
          </Select.Content>
        </Select.Positioner>
      </Select.Root>
      <button type="submit">Submit</button>
    </form>
  );
};

// libs/solid/examples/select/form-library.tsx
import { Select, createListCollection } from "@ark-ui/solid";
import { createForm, getValue, setValue } from "@modular-forms/solid";
import { createMemo } from "solid-js";
import { Index, Portal } from "solid-js/web";

export const WithFormLibrary = () => {
  const frameworks = createListCollection({
    items: [
      { label: "React", value: "react" },
      { label: "Solid", value: "solid" },
      { label: "Vue", value: "vue" }
    ]
  });

  const [formStore, { Form, Field }] = createForm({
    initialValues: { value: "solid" }
  });

  const value = createMemo(() => getValue(formStore, "value"));

  return (
    <>
      <div>Value is {value()}</div>
      <Form
        onSubmit={(e) => {
          console.log(e.value);
        }}
      >
        <Field name="value">
          {(field, props) => (
            <Select.Root
              collection={frameworks}
              value={field.value ? [field.value] : []}
              invalid={!!field.error}
              name={field.name}
              onValueChange={(e) => {
                setValue(formStore, field.name, e.value[0]);
              }}
            >
              <Select.Control>
                <Select.Trigger>
                  <Select.ValueText placeholder="Select a Framework" />
                </Select.Trigger>
                <Select.ClearTrigger>Clear</Select.ClearTrigger>
              </Select.Control>
              <Portal>
                <Select.Positioner>
                  <Select.Content>
                    <Select.ItemGroup>
                      <Select.ItemGroupLabel>Frameworks</Select.ItemGroupLabel>
                      <Index each={frameworks.items}>
                        {(item) => (
                          <Select.Item item={item()}>
                            <Select.ItemText>{item().label}</Select.ItemText>
                            <Select.ItemIndicator>✓</Select.ItemIndicator>
                          </Select.Item>
                        )}
                      </Index>
                    </Select.ItemGroup>
                  </Select.Content>
                </Select.Positioner>
              </Portal>
              <Select.HiddenSelect {...props} />
            </Select.Root>
          )}
        </Field>
        <button type="submit">Submit</button>
      </Form>
    </>
  );
};
