// examples/react/src/select/reactive-collection.tsx
import { Select, createListCollection } from "@ark-ui/react/select";
import { minimal, park, shadcn } from "@spark-css/themes";
import { clsx } from "clsx";
import { CheckIcon, ChevronsUpDownIcon } from "lucide-react";
import { useState } from "react";
import { type Theme, getTheme } from "../utils";

const itemsBase = [
  { label: "React", value: "react" },
  { label: "Solid", value: "solid" },
  { label: "Svelte", value: "svelte", disabled: true },
  { label: "Vue", value: "vue" }
];

export const ReactiveCollection = ({ theme }: { theme: Theme }) => {
  const styledSlots = getTheme({ minimal: minimal.select, park: park.select, shadcn: shadcn.select }, theme);
  const [number, setNumber] = useState(0);
  const collection = createListCollection({
    items: itemsBase.map((item) => ({ ...item, label: `${item.label}-${number}` }))
  });

  return (
    <div>
      <button type="button" onClick={() => setNumber(number + 1)}>
        Inc
      </button>
      <button type="button" onClick={() => setNumber(number - 1)}>
        Dec
      </button>

      <Select.Root positioning={{ sameWidth: true }} collection={collection}>
        <Select.Label>Framework</Select.Label>
        <Select.Control>
          <Select.Trigger>
            <Select.ValueText placeholder="Select a Framework" />
            <ChevronsUpDownIcon />
          </Select.Trigger>
        </Select.Control>
        <Select.Positioner>
          <Select.Content>
            <Select.ItemGroup>
              <Select.ItemGroupLabel>Framework</Select.ItemGroupLabel>
              {collection.items.map((item) => (
                <Select.Item item={item} key={item.label}>
                  <Select.ItemText>{item.label}</Select.ItemText>
                  <Select.ItemIndicator>
                    <CheckIcon />
                  </Select.ItemIndicator>
                </Select.Item>
              ))}
            </Select.ItemGroup>
          </Select.Content>
        </Select.Positioner>
      </Select.Root>
    </div>
  );
};

// libs/solid/examples/select/reactive-collection.tsx
import { Select, createListCollection } from "@ark-ui/solid/select";
import { CheckIcon, ChevronsUpDownIcon } from "lucide-solid";
import { createMemo, createSignal } from "solid-js";
import { Index } from "solid-js/web";

const items = [
  { label: "React", value: "react" },
  { label: "Solid", value: "solid" },
  { label: "Svelte", value: "svelte", disabled: true },
  { label: "Vue", value: "vue" }
];

export const ReactiveCollection = () => {
  const [number, setNumber] = createSignal(0);

  const collection = createMemo(() =>
    createListCollection({
      items: items.map((item) => ({ ...item, label: `${item.label}-${number()}` }))
    })
  );

  return (
    <div>
      <button type="button" onClick={() => setNumber(number() + 1)}>
        Inc
      </button>
      <button type="button" onClick={() => setNumber(number() - 1)}>
        Dec
      </button>

      <Select.Root positioning={{ sameWidth: true }} collection={collection()}>
        <Select.Label>Framework</Select.Label>
        <Select.Control>
          <Select.Trigger>
            <Select.ValueText placeholder="Select a Framework" />
            <ChevronsUpDownIcon />
          </Select.Trigger>
        </Select.Control>
        <Select.Positioner>
          <Select.Content>
            <Select.ItemGroup>
              <Select.ItemGroupLabel>Framework</Select.ItemGroupLabel>
              <Index each={collection().items}>
                {(item) => (
                  <Select.Item item={item()}>
                    <Select.ItemText>{item().label}</Select.ItemText>
                    <Select.ItemIndicator>
                      <CheckIcon />
                    </Select.ItemIndicator>
                  </Select.Item>
                )}
              </Index>
            </Select.ItemGroup>
          </Select.Content>
        </Select.Positioner>
      </Select.Root>
    </div>
  );
};
