// playground/svelte/src/lib/bits-ui/alert-dialog/index.svelte
<script lang="ts">
import { AlertDialog } from "bits-ui";
</script>

<AlertDialog.Root>
  <AlertDialog.Trigger>
    Subscribe
  </AlertDialog.Trigger>
  <AlertDialog.Portal>
    <AlertDialog.Overlay />
    <AlertDialog.Content>
      <div >
        <AlertDialog.Title >
          Confirm your transaction
        </AlertDialog.Title>
        <AlertDialog.Description >
          This action cannot be undone. This will initiate a monthly wire in the
          amount of $10,000 to Huntabyte. Do you wish to continue?
        </AlertDialog.Description>
      </div>
      <div >
        <AlertDialog.Cancel>
          Cancel
        </AlertDialog.Cancel>
        <AlertDialog.Action>
          Continue
        </AlertDialog.Action>
      </div>
    </AlertDialog.Content>
  </AlertDialog.Portal>
</AlertDialog.Root>

// playground/react/src/radix-ui/alert-dialog/index.tsx
import * as AlertDialog from "@radix-ui/react-alert-dialog";

export const Basic = () => (
  <AlertDialog.Root>
    <AlertDialog.Trigger>delete everything</AlertDialog.Trigger>
    <AlertDialog.Portal>
      <AlertDialog.Overlay />
      <AlertDialog.Content>
        <AlertDialog.Title>Are you sure?</AlertDialog.Title>
        <AlertDialog.Description>This will do a very dangerous thing. Thar be dragons!</AlertDialog.Description>
        <AlertDialog.Action>yolo, do it</AlertDialog.Action>
        <AlertDialog.Cancel>maybe not</AlertDialog.Cancel>
      </AlertDialog.Content>
    </AlertDialog.Portal>
  </AlertDialog.Root>
);
