// libs/react/examples/avatar/closed.tsx
import { Avatar as ArkAvatar } from "@ark-ui/react/avatar";
import { UserIcon } from "lucide-react";
import { forwardRef } from "react";

export interface AvatarProps extends ArkAvatar.RootProps {
  name?: string;
  src?: string;
}

export const Avatar = forwardRef<HTMLDivElement, AvatarProps>((props, ref) => {
  const { name, src, ...rootProps } = props;
  return (
    <ArkAvatar.Root ref={ref} {...rootProps}>
      <ArkAvatar.Fallback>{getInitials(name) || <UserIcon />}</ArkAvatar.Fallback>
      <ArkAvatar.Image src={src} alt={name} />
    </ArkAvatar.Root>
  );
});

const getInitials = (name = "") =>
  name
    .split(" ")
    .map((part) => part[0])
    .slice(0, 2)
    .join("")
    .toUpperCase();

// libs/solid/examples/avatar/closed.tsx
import { Avatar as ArkAvatar } from "@ark-ui/solid/avatar";
import { UserIcon } from "lucide-solid";
import { Show, splitProps } from "solid-js";

export interface AvatarProps extends ArkAvatar.RootProps {
  name?: string;
  src?: string;
}

export const Avatar = (props: AvatarProps) => {
  const [localProps, rootProps] = splitProps(props, ["name", "src"]);

  return (
    <ArkAvatar.Root {...rootProps}>
      <ArkAvatar.Fallback>
        <Show when={localProps.name} fallback={<UserIcon />}>
          {getInitials(localProps.name)}
        </Show>
      </ArkAvatar.Fallback>
      <ArkAvatar.Image src={localProps.src} alt={localProps.name} />
    </ArkAvatar.Root>
  );
};

const getInitials = (name = "") =>
  name
    .split(" ")
    .map((part) => part[0])
    .splice(0, 2)
    .join("")
    .toUpperCase();
