// examples/vue/src/clipboard/root-provider.vue
<script setup lang="ts">
import { Clipboard, useClipboard } from "@ark-ui/vue/clipboard";
import { Check, ClipboardCopy } from "lucide-vue-next";

const clipboard = useClipboard({ value: "https.//ark-ui.com" });
</script>

<template>
  <button @click="clipboard.copy()">Copy</button>

  <Clipboard.RootProvider :value="clipboard">
    <Clipboard.Label>Copy this link</Clipboard.Label>
    <Clipboard.Control>
      <Clipboard.Input />
      <Clipboard.Trigger>
        <Clipboard.Indicator>
          <ClipboardCopy />
          <template #copied>
            <Check />
          </template>
        </Clipboard.Indicator>
      </Clipboard.Trigger>
    </Clipboard.Control>
  </Clipboard.RootProvider>
</template>

// libs/react/examples/checkbox/root-provider.tsx
import { Checkbox, useCheckbox } from "@ark-ui/react/checkbox";
import { CheckIcon } from "lucide-react";

export const RootProvider = () => {
  const checkbox = useCheckbox();

  return (
    <>
      <span>{checkbox.checked ? "Checked" : "UnChecked"}</span>

      <Checkbox.RootProvider value={checkbox}>
        <Checkbox.Label>Checkbox</Checkbox.Label>
        <Checkbox.Control>
          <Checkbox.Indicator>
            <CheckIcon />
          </Checkbox.Indicator>
        </Checkbox.Control>
        <Checkbox.HiddenInput />
      </Checkbox.RootProvider>
    </>
  );
};
