// playground/react/src/radix-ui/radio-group/index.tsx
import { Label } from "@radix-ui/react-label";
import * as RadioGroup from "@radix-ui/react-radio-group";

export const Basic = () => (
  <Label>
    Favourite pet
    <RadioGroup.Root defaultValue="1">
      <Label>
        <RadioGroup.Item value="1">
          <RadioGroup.Indicator />
        </RadioGroup.Item>
        Cat
      </Label>{" "}
      <Label>
        <RadioGroup.Item value="2">
          <RadioGroup.Indicator />
        </RadioGroup.Item>
        Dog
      </Label>{" "}
      <Label>
        <RadioGroup.Item value="3">
          <RadioGroup.Indicator />
        </RadioGroup.Item>
        Rabbit
      </Label>
    </RadioGroup.Root>
  </Label>
);

// playground/svelte/src/lib/bits-ui/radio-group/index.svelte
<script lang="ts">
import { Label, RadioGroup } from "bits-ui";
</script>
 
<RadioGroup.Root>
  <div
   
  >
    <RadioGroup.Item
      id="amazing"
      value="amazing"
     
    />
    <Label.Root for="amazing">Amazing</Label.Root>
  </div>
  <div
   
  >
    <RadioGroup.Item
      id="average"
      value="average"
     
    />
    <Label.Root for="average">Average</Label.Root>
  </div>
  <div
   
  >
    <RadioGroup.Item
      id="terrible"
      value="terrible"
     
    />
    <Label.Root for="terrible">Terrible</Label.Root>
  </div>
</RadioGroup.Root>
