// libs/solid/examples/checkbox/controlled.tsx
import { Checkbox } from "@ark-ui/solid/checkbox";
import { CheckIcon } from "lucide-solid";
import { createSignal } from "solid-js";

export const Controlled = () => {
  const [checked, setChecked] = createSignal<Checkbox.CheckedState>(true);
  return (
    <Checkbox.Root checked={checked()} onCheckedChange={(e) => setChecked(e.checked)}>
      <Checkbox.Label>Checkbox</Checkbox.Label>
      <Checkbox.Control>
        <Checkbox.Indicator>
          <CheckIcon />
        </Checkbox.Indicator>
      </Checkbox.Control>
      <Checkbox.HiddenInput />
    </Checkbox.Root>
  );
};

// examples/vue/src/checkbox/controlled.vue
<script setup lang="ts">
import { Checkbox, type CheckboxCheckedState } from "@ark-ui/vue/checkbox";
import { Check } from "lucide-vue-next";
import { ref } from "vue";

const checked = ref<CheckboxCheckedState>(true);
</script>

<template>
  <Checkbox.Root v-model:checked="checked">
    <Checkbox.Label>Checkbox</Checkbox.Label>
    <Checkbox.Control>
      <Checkbox.Indicator>
        <Check />
      </Checkbox.Indicator>
    </Checkbox.Control>
    <Checkbox.HiddenInput />
  </Checkbox.Root>
</template>
