// libs/vue/examples/qr-code/with-overlay.vue
<script setup lang="ts">
import { QrCode } from "@ark-ui/vue/qr-code";
</script>

<template>
  <QrCode.Root defaultValue="http://ark-ui.com">
    <QrCode.Frame>
      <QrCode.Pattern />
    </QrCode.Frame>
    <QrCode.Overlay>
      <img src="https://ark-ui.com/icon-192.png" alt="Ark UI Logo" />
    </QrCode.Overlay>
  </QrCode.Root>
</template>

// libs/solid/examples/qr-code/with-overlay.tsx
import { QrCode } from "@ark-ui/solid/qr-code";

export const WithOverlay = () => {
  return (
    <QrCode.Root defaultValue="http://ark-ui.com">
      <QrCode.Frame>
        <QrCode.Pattern />
      </QrCode.Frame>
      <QrCode.Overlay>
        <img src="https://ark-ui.com/icon-192.png" alt="Ark UI Logo" />
      </QrCode.Overlay>
    </QrCode.Root>
  );
};
