// playground/react/src/ark-ui/listbox/index.tsx
import { Listbox, createListCollection } from "@ark-ui/react/listbox";

export const Basic = () => {
  const collection = createListCollection({ items: ["React", "Solid", "Vue"] });

  return (
    <Listbox.Root collection={collection}>
      <Listbox.Label>Select your Framework</Listbox.Label>
      <Listbox.Content>
        {collection.items.map((item) => (
          <Listbox.Item key={item} item={item}>
            <Listbox.ItemText>{item}</Listbox.ItemText>
            <Listbox.ItemIndicator />
          </Listbox.Item>
        ))}
      </Listbox.Content>
    </Listbox.Root>
  );
};

// playground/vue/src/ark-ui/listbox/index.vue
<script setup lang="ts">
import { Listbox, createListCollection } from "@ark-ui/vue/listbox";

const collection = createListCollection({
  items: ["React", "Solid", "Vue"],
});
</script>

<template>
  <Listbox.Root :collection="collection">
    <Listbox.Label>Framework</Listbox.Label>
    <Listbox.Content>
      <Listbox.Item v-for="item in collection.items" :key="item" :item="item">
        <Listbox.ItemText>{{ item }}</Listbox.ItemText>
        <Listbox.ItemIndicator />
      </Listbox.Item>
    </Listbox.Content>
  </Listbox.Root>
</template>
