// playground/vue/src/progress/circular/index.vue
<script setup lang="ts">
import { Progress } from "@ark-ui/vue/progress";
</script>

<template>
  <Progress.Root>
    <Progress.Label>Label</Progress.Label>
    <Progress.ValueText />
    <Progress.Circle>
      <Progress.CircleTrack />
      <Progress.CircleRange />
    </Progress.Circle>
  </Progress.Root>
</template>

// playground/react/src/progress/circular/index.tsx
import { Progress } from "@ark-ui/react/progress";

export const Basic = () => {
  return (
    <Progress.Root>
      <Progress.Label>Label</Progress.Label>
      <Progress.ValueText />
      <Progress.Circle>
        <Progress.CircleTrack />
        <Progress.CircleRange />
      </Progress.Circle>
    </Progress.Root>
  );
};
