// playground/react/src/ark-ui/splitter/index.tsx
import { Splitter } from "@ark-ui/react/splitter";

export const Basic = () => {
  return (
    <Splitter.Root panels={[{ id: "a" }, { id: "b" }]}>
      <Splitter.Panel id="a">A</Splitter.Panel>
      <Splitter.ResizeTrigger id="a:b" />
      <Splitter.Panel id="b">B</Splitter.Panel>
    </Splitter.Root>
  );
};

// playground/vue/src/ark-ui/splitter/index.vue
<script setup lang="ts">
import { Splitter } from "@ark-ui/vue/splitter";
</script>

<template>
  <Splitter.Root :panels="[{ id: 'a' }, { id: 'b' }]">
    <Splitter.Panel id="a">A</Splitter.Panel>
    <Splitter.ResizeTrigger id="a:b" />
    <Splitter.Panel id="b">B</Splitter.Panel>
  </Splitter.Root>
</template>
