// examples/react/src/field/textarea.tsx
import { Field } from "@ark-ui/react/field";
import { minimal, park, shadcn } from "@spark-css/themes";
import { clsx } from "clsx";
import { type Theme, getTheme } from "../utils";

export const Textarea = ({ theme }: { theme: Theme }) => {
  const styledSlots = getTheme(
    { minimal: minimal.field, park: park.field, shadcn: shadcn.field },
    theme
  );

  return (
    <Field.Root className={clsx(styledSlots.root)}>
      <Field.Label className={clsx(styledSlots.label)}>Label</Field.Label>
      <Field.Textarea autoresize className={clsx(styledSlots.textarea)} />
      <Field.HelperText className={clsx(styledSlots.helperText)}>Some additional Info</Field.HelperText>
      <Field.ErrorText className={clsx(styledSlots.errorText)}>Error Info</Field.ErrorText>
    </Field.Root>
  );
};

// playground/vue/src/ark-ui/field/textarea.vue
<script setup lang="ts">
import { Field } from "@ark-ui/vue/field";
</script>

<template>
  <Field.Root>
    <Field.Label>Label</Field.Label>
    <Field.Textarea autoresize />
    <Field.HelperText>Some additional Info</Field.HelperText>
    <Field.ErrorText>Error Info</Field.ErrorText>
  </Field.Root>
</template>
