// examples/solid/src/hover-card/render-prop.tsx
import { HoverCard } from "@ark-ui/solid/hover-card";
import { Portal } from "solid-js/web";

export const RenderProp = () => (
  <HoverCard.Root>
    <HoverCard.Context>
      {(context) => <HoverCard.Trigger>Hover me {context().open ? "▲" : "▼"} </HoverCard.Trigger>}
    </HoverCard.Context>
    <Portal>
      <HoverCard.Positioner>
        <HoverCard.Content>
          <HoverCard.Arrow>
            <HoverCard.ArrowTip />
          </HoverCard.Arrow>
          Content
        </HoverCard.Content>
      </HoverCard.Positioner>
    </Portal>
  </HoverCard.Root>
);

// examples/solid/src/menu/render-prop.tsx
import { Menu } from "@ark-ui/solid/menu";

export const RenderProp = () => (
  <Menu.Root>
    <Menu.Context>
      {(context) => <Menu.Trigger>Menu is {context().open ? "open" : "closed"}</Menu.Trigger>}
    </Menu.Context>
    <Menu.Positioner>
      <Menu.Content>
        <Menu.Item value="react">React</Menu.Item>
        <Menu.Item value="solid">
          <Menu.ItemContext>
            {(context) => <>Solid is {context().highlighted ? "highlighted" : "not highlighted"}</>}
          </Menu.ItemContext>
        </Menu.Item>
        <Menu.Item value="vue">Vue</Menu.Item>
      </Menu.Content>
    </Menu.Positioner>
  </Menu.Root>
);
