// libs/solid/examples/hover-card/root-provider.tsx
import { HoverCard, useHoverCard } from "@ark-ui/solid/hover-card";
import { Portal } from "solid-js/web";

export const RootProvider = () => {
  const hoverCard = useHoverCard();

  return (
    <>
      <button type="button" onClick={() => hoverCard().setOpen(true)}>
        Open
      </button>

      <HoverCard.RootProvider value={hoverCard}>
        <HoverCard.Trigger>Hover me</HoverCard.Trigger>
        <Portal>
          <HoverCard.Positioner>
            <HoverCard.Content>
              <HoverCard.Arrow>
                <HoverCard.ArrowTip />
              </HoverCard.Arrow>
              Content
            </HoverCard.Content>
          </HoverCard.Positioner>
        </Portal>
      </HoverCard.RootProvider>
    </>
  );
};

// examples/solid/src/menu/root-provider.tsx
import { Menu, useMenu } from "@ark-ui/solid/menu";

export const RootProvider = () => {
  const menu = useMenu();

  return (
    <>
      <button type="button" onClick={() => menu.api().setHighlightedValue("solid")}>
        Highlight Solid
      </button>

      <Menu.Root>
        <Menu.Trigger>
          Open menu <Menu.Indicator>➡️</Menu.Indicator>
        </Menu.Trigger>
        <Menu.Positioner>
          <Menu.Content>
            <Menu.Item value="react">React</Menu.Item>
            <Menu.Item value="solid">Solid</Menu.Item>
            <Menu.Item value="vue">Vue</Menu.Item>
          </Menu.Content>
        </Menu.Positioner>
      </Menu.Root>
    </>
  );
};
