// playground/svelte/src/lib/ark-ui/qr-code/index.svelte
<script lang="ts">
import { QrCode } from "@ark-ui/svelte/qr-code";
</script>

<QrCode.Root id="qr-code-root" defaultValue="http://ark-ui.com">
  <QrCode.Frame>
    <QrCode.Pattern />
  </QrCode.Frame>
  <QrCode.DownloadTrigger fileName="qr-code.png" mimeType="image/png">Download</QrCode.DownloadTrigger>
</QrCode.Root>

// playground/react/src/ark-ui/qr-code/index.tsx
import { QrCode } from "@ark-ui/react/qr-code";

export const Basic = () => {
  return (
    <QrCode.Root defaultValue="http://ark-ui.com">
      <QrCode.Frame>
        <QrCode.Pattern />
      </QrCode.Frame>
      <QrCode.DownloadTrigger fileName="qr-code.png" mimeType="image/png">
        Download
      </QrCode.DownloadTrigger>
    </QrCode.Root>
  );
};
