// libs/solid/examples/slider/root-provider.tsx
import { Slider, useSlider } from "@ark-ui/solid/slider";

export const RootProvider = () => {
  const slider = useSlider();

  return (
    <>
      <button type="button" onClick={() => slider().focus()}>
        Focus
      </button>

      <Slider.RootProvider value={slider}>
        <Slider.Label>Label</Slider.Label>
        <Slider.ValueText />
        <Slider.Control>
          <Slider.Track>
            <Slider.Range />
          </Slider.Track>
          <Slider.Thumb index={0}>
            <Slider.HiddenInput />
          </Slider.Thumb>
        </Slider.Control>
      </Slider.RootProvider>
    </>
  );
};

// libs/solid/examples/radio-group/root-provider.tsx
import { RadioGroup, useRadioGroup } from "@ark-ui/solid/radio-group";
import { Index } from "solid-js";

export const RootProvider = () => {
  const frameworks = ["React", "Solid", "Vue"];

  const radioGroup = useRadioGroup();

  return (
    <>
      <button type="button" onClick={() => radioGroup().focus()}>
        Focus
      </button>

      <RadioGroup.RootProvider value={radioGroup}>
        <RadioGroup.Label>Framework</RadioGroup.Label>
        <RadioGroup.Indicator />
        <Index each={frameworks}>
          {(framework) => (
            <RadioGroup.Item value={framework()}>
              <RadioGroup.ItemText>{framework()}</RadioGroup.ItemText>
              <RadioGroup.ItemControl />
              <RadioGroup.ItemHiddenInput />
            </RadioGroup.Item>
          )}
        </Index>
      </RadioGroup.RootProvider>
    </>
  );
};
