// examples/solid/src/dialog/render-fn.tsx
import { Dialog } from "@ark-ui/solid/dialog";
import { Portal } from "solid-js/web";

export const RenderFn = () => {
  return (
    <Dialog.Root>
      <Dialog.Trigger>Open Dialog</Dialog.Trigger>
      <Portal>
        <Dialog.Backdrop />
        <Dialog.Positioner>
          <Dialog.Content>
            <Dialog.Title>Dialog Title</Dialog.Title>
            <Dialog.Description>Dialog Description</Dialog.Description>
            <Dialog.CloseTrigger>Close</Dialog.CloseTrigger>
          </Dialog.Content>
        </Dialog.Positioner>
      </Portal>
      <Dialog.Context>{(context) => <p>Dialog is {context().open ? "open" : "closed"}</p>}</Dialog.Context>
    </Dialog.Root>
  );
};

// libs/react/examples/popover/render-fn.tsx
import { Popover } from "@ark-ui/react/popover";

export const RenderFn = () => (
  <Popover.Root>
    <Popover.Trigger>Click Me</Popover.Trigger>
    <Popover.Positioner>
      <Popover.Context>
        {(popover) => (
          <Popover.Content>
            <Popover.Title>Title</Popover.Title>
            <Popover.Description>Description: {popover.open.toString()}</Popover.Description>
            <Popover.CloseTrigger>Close</Popover.CloseTrigger>
          </Popover.Content>
        )}
      </Popover.Context>
    </Popover.Positioner>
  </Popover.Root>
);
