// examples/vue/src/accordion/context/setValue.vue
<script setup lang="ts">
import { Accordion } from "@ark-ui/vue/accordion";
import { ChevronDown } from "lucide-vue-next";
import { ref } from "vue";

const items = ref(["React", "Solid", "Vue"]);
</script>

<template>
  <Accordion.Root :defaultValue="['React']">
    <Accordion.Context v-slot="context">
      <button @click="context.setValue(['Vue'])">Select Vue</button>
    </Accordion.Context>
    <Accordion.Item v-for="item in items" :key="item" :value="item">
      <Accordion.ItemTrigger>
        What is {{ item }}?
        <Accordion.ItemIndicator>
          <ChevronDown />
        </Accordion.ItemIndicator>
      </Accordion.ItemTrigger>
      <Accordion.ItemContent
        >{{ item }} is a JavaScript library for building user
        interfaces.</Accordion.ItemContent
      >
    </Accordion.Item>
  </Accordion.Root>
</template>

// libs/react/examples/accordion/context/setValue.tsx
import { Accordion } from "@ark-ui/react/accordion";
import { ChevronDownIcon } from "lucide-react";

export const ContextSetValue = () => {
  return (
    <Accordion.Root defaultValue={["React"]}>
      <Accordion.Context>
        {(context) => (
          <button type="button" onClick={() => context.setValue(["Vue"])}>
            Select Vue
          </button>
        )}
      </Accordion.Context>
      {["React", "Solid", "Vue"].map((item) => (
        <Accordion.Item key={item} value={item}>
          <Accordion.ItemTrigger>
            What is {item}?
            <Accordion.ItemIndicator>
              <ChevronDownIcon />
            </Accordion.ItemIndicator>
          </Accordion.ItemTrigger>
          <Accordion.ItemContent>{item} is a JavaScript library for building user interfaces.</Accordion.ItemContent>
        </Accordion.Item>
      ))}
    </Accordion.Root>
  );
};
