// examples/react/src/pin-input/with-mask.tsx
import { PinInput } from "@ark-ui/react/pin-input";
import { minimal, park, shadcn } from "@spark-css/themes";
import { clsx } from "clsx";
import { type Theme, getTheme } from "../utils";

export const WithMask = ({ theme }: { theme: Theme }) => {
  const styledSlots = getTheme({ minimal: minimal.pinInput, park: park.pinInput, shadcn: shadcn.pinInput }, theme);

  return (
    <PinInput.Root mask>
      <PinInput.Label>Label</PinInput.Label>
      <PinInput.Control>
        {[0, 1, 2].map((id, index) => (
          <PinInput.Input key={id} index={index} />
        ))}
      </PinInput.Control>
      <PinInput.HiddenInput />
    </PinInput.Root>
  );
};

// examples/solid/src/pin-input/with-mask.tsx
import { PinInput } from "@ark-ui/solid/pin-input";
import { Index } from "solid-js";

export const WithMask = () => (
  <PinInput.Root mask>
    <PinInput.Label>Label</PinInput.Label>
    <PinInput.Control>
      <Index each={[0, 1, 2]}>{(id) => <PinInput.Input index={id()} />}</Index>
    </PinInput.Control>
    <PinInput.HiddenInput />
  </PinInput.Root>
);
