// libs/vue/examples/clipboard/basic.vue
<script setup lang="ts">
import { Clipboard } from "@ark-ui/vue/clipboard";
import { default as CheckIcon } from "../icons/check.vue";
import { default as ClipboardCopyIcon } from "../icons/clipboard-copy.vue";
</script>

<template>
  <Clipboard.Root value="https.//ark-ui.com">
    <Clipboard.Label>Copy this link</Clipboard.Label>
    <Clipboard.Control>
      <Clipboard.Input />
      <Clipboard.Trigger>
        <Clipboard.Indicator>
          <ClipboardCopyIcon />
          <template #copied>
            <CheckIcon />
          </template>
        </Clipboard.Indicator>
      </Clipboard.Trigger>
    </Clipboard.Control>
  </Clipboard.Root>
</template>

// libs/solid/examples/clipboard/basic.tsx
import { Clipboard } from "@ark-ui/solid/clipboard";
import { CheckIcon, ClipboardCopyIcon } from "lucide-solid";

export const Basic = () => {
  return (
    <Clipboard.Root value="https://ark-ui.com">
      <Clipboard.Label>Copy this link</Clipboard.Label>
      <Clipboard.Control>
        <Clipboard.Input />
        <Clipboard.Trigger>
          <Clipboard.Indicator copied={<CheckIcon />}>
            <ClipboardCopyIcon />
          </Clipboard.Indicator>
        </Clipboard.Trigger>
      </Clipboard.Control>
    </Clipboard.Root>
  );
};
