// playground/svelte/src/lib/ark-ui/slider/index.svelte
<script lang="ts">
import { Slider } from "@ark-ui/svelte/slider";
</script>

<Slider.Root id="slider-root">
  <Slider.Label>Label</Slider.Label>
  <Slider.ValueText />
  <Slider.Control>
    <Slider.Track>
      <Slider.Range />
    </Slider.Track>
    <Slider.Thumb index={0}>
      <Slider.HiddenInput />
    </Slider.Thumb>
  </Slider.Control>
</Slider.Root>

// playground/react/src/base-ui/slider/index.tsx
import { Slider } from "@base-ui-components/react/slider";

export const Basic = () => {
  return (
    <Slider.Root defaultValue={25}>
      <Slider.Control>
        <Slider.Track>
          <Slider.Indicator />
          <Slider.Thumb />
        </Slider.Track>
      </Slider.Control>
    </Slider.Root>
  );
};
