// examples/solid/src/tooltip/positioning.tsx
import { Tooltip } from "@ark-ui/solid/tooltip";
import { Portal } from "solid-js/web";

export const Positioning = () => (
  <Tooltip.Root
    positioning={{
      placement: "left-start",
      offset: { mainAxis: 12, crossAxis: 12 }
    }}
  >
    <Tooltip.Trigger>Hover Me</Tooltip.Trigger>
    <Portal>
      <Tooltip.Positioner>
        <Tooltip.Content>I am a tooltip!</Tooltip.Content>
      </Tooltip.Positioner>
    </Portal>
  </Tooltip.Root>
);

// libs/react/examples/tooltip/positioning.tsx
import { Tooltip } from "@ark-ui/react/tooltip";

export const Positioning = () => (
  <Tooltip.Root
    positioning={{
      placement: "left-start",
      offset: { mainAxis: 12, crossAxis: 12 }
    }}
  >
    <Tooltip.Trigger>Hover Me</Tooltip.Trigger>
    <Tooltip.Positioner>
      <Tooltip.Content>I am a tooltip!</Tooltip.Content>
    </Tooltip.Positioner>
  </Tooltip.Root>
);
