// libs/solid/examples/carousel/basic.tsx
import { Carousel } from "@ark-ui/solid/carousel";
import { Index } from "solid-js";

export const Basic = () => {
  const images = [
    "https://tinyurl.com/5b6ka8jd",
    "https://tinyurl.com/7rmccdn5",
    "https://tinyurl.com/59jxz9uu",
    "https://tinyurl.com/6jurv23t",
    "https://tinyurl.com/yp4rfum7"
  ];
  return (
    <Carousel.Root>
      <Carousel.Control>
        <Carousel.PrevTrigger>Previous</Carousel.PrevTrigger>
        <Carousel.NextTrigger>Next</Carousel.NextTrigger>
      </Carousel.Control>
      <Carousel.IndicatorGroup>
        <Index each={images}>{(_, index) => <Carousel.Indicator index={index}>{index + 1}</Carousel.Indicator>}</Index>
      </Carousel.IndicatorGroup>
      <Carousel.Viewport>
        <Carousel.ItemGroup>
          <Index each={images}>
            {(image, index) => (
              <Carousel.Item index={index}>
                <img src={image()} alt={`Slide ${index}`} />
              </Carousel.Item>
            )}
          </Index>
        </Carousel.ItemGroup>
      </Carousel.Viewport>
    </Carousel.Root>
  );
};

// examples/vue/src/carousel/basic.vue
<script setup lang="ts">
import { Carousel } from "@ark-ui/vue/carousel";

const images = Array.from({ length: 5 }, (_, i) => `https://picsum.photos/seed/${i + 1}/500/300`);
</script>

<template>
  <Carousel.Root :slide-count="images.length">
    <Carousel.Control>
      <Carousel.PrevTrigger>Previous</Carousel.PrevTrigger>
      <Carousel.NextTrigger>Next</Carousel.NextTrigger>
    </Carousel.Control>
    <Carousel.IndicatorGroup>
      <Carousel.Indicator v-for="(_, idx) in images" :key="idx" :index="idx" />
    </Carousel.IndicatorGroup>
    <Carousel.ItemGroup>
      <Carousel.Item v-for="(image, idx) in images" :key="idx" :index="idx">
        <img
          :src="image"
          alt=""
          :style="{ height: '300px', width: '100%', objectFit: 'cover' }"
        />
      </Carousel.Item>
    </Carousel.ItemGroup>
  </Carousel.Root>
</template>
