// libs/vue/examples/checkbox/indeterminate.vue
<script setup lang="ts">
import { Checkbox } from "@ark-ui/vue/checkbox";
import { default as CheckIcon } from "../icons/check.vue";
import { default as MinusIcon } from "../icons/minus.vue";
</script>

<template>
  <Checkbox.Root checked="indeterminate">
    <Checkbox.Label>Checkbox</Checkbox.Label>
    <Checkbox.Control>
      <Checkbox.Indicator>
        <CheckIcon />
      </Checkbox.Indicator>
      <Checkbox.Indicator indeterminate>
        <MinusIcon />
      </Checkbox.Indicator>
    </Checkbox.Control>
    <Checkbox.HiddenInput />
  </Checkbox.Root>
</template>

// examples/solid/src/checkbox/indeterminate.tsx
import { Checkbox } from "@ark-ui/solid/checkbox";
import { CheckIcon, MinusIcon } from "lucide-solid";

export const Indeterminate = () => (
  <Checkbox.Root checked="indeterminate">
    <Checkbox.Label>Checkbox</Checkbox.Label>
    <Checkbox.Control>
      <Checkbox.Indicator>
        <CheckIcon />
      </Checkbox.Indicator>
      <Checkbox.Indicator indeterminate>
        <MinusIcon />
      </Checkbox.Indicator>
    </Checkbox.Control>
    <Checkbox.HiddenInput />
  </Checkbox.Root>
);
