// examples/solid/src/qr-code/controlled.tsx
import { QrCode } from "@ark-ui/solid/qr-code";
import { createSignal } from "solid-js";

export const Controlled = () => {
  const [value, setValue] = createSignal("http://ark-ui.com");

  return (
    <QrCode.Root value={value()} onValueChange={(e) => setValue(e.value)}>
      <QrCode.Frame>
        <QrCode.Pattern />
      </QrCode.Frame>
    </QrCode.Root>
  );
};

// examples/vue/src/qr-code/controlled.vue
<script setup lang="ts">
import { QrCode } from "@ark-ui/vue/qr-code";
import { ref } from "vue";

const value = ref("http://ark-ui.com");
</script>

<template>
  <QrCode.Root v-model="value">
    <QrCode.Frame>
      <QrCode.Pattern />
    </QrCode.Frame>
    <QrCode.DownloadTrigger fileName="qr-code.png" mimeType="image/png">
      Download
    </QrCode.DownloadTrigger>
  </QrCode.Root>
</template>
