// examples/vue/src/qr-code/error-correction.vue
<script setup lang="ts">
import { QrCode, type QrCodeGenerateOptions } from "@ark-ui/vue/qr-code";
import { ref } from "vue";

const encoding = ref<QrCodeGenerateOptions>({ ecc: "H" });
</script>

<template>
  <QrCode.Root defaultValue="http://ark-ui.com" :encoding="encoding">
    <QrCode.Frame>
      <QrCode.Pattern />
    </QrCode.Frame>
  </QrCode.Root>
</template>

// examples/react/src/qr-code/error-correction.tsx
import { QrCode } from "@ark-ui/react/qr-code";
import { minimal, park, shadcn } from "@spark-css/themes";
import { clsx } from "clsx";
import { type Theme, getTheme } from "../utils";

export const ErrorCorrection = ({ theme }: { theme: Theme }) => {
  const styledSlots = getTheme({ minimal: minimal.qrCode, park: park.qrCode, shadcn: shadcn.qrCode }, theme);

  return (
    <QrCode.Root defaultValue="http://ark-ui.com" encoding={{ ecc: "H" }}>
      <QrCode.Frame>
        <QrCode.Pattern />
      </QrCode.Frame>
    </QrCode.Root>
  );
};
