// examples/vue/src/carousel/autoplay.vue
<script setup lang="ts">
import { Carousel } from "@ark-ui/vue/carousel";

const images = Array.from({ length: 5 }, (_, i) => `https://picsum.photos/seed/${i + 1}/500/300`);
</script>

<template>
  <Carousel.Root :slide-count="images.length" autoplay loop>
    <Carousel.Control>
      <Carousel.AutoplayTrigger>
        <Carousel.Context v-slot="context">
          {{ context.isPlaying ? "Pause" : "Play" }}
        </Carousel.Context>
      </Carousel.AutoplayTrigger>
    </Carousel.Control>
    <Carousel.IndicatorGroup>
      <Carousel.Indicator v-for="(_, idx) in images" :key="idx" :index="idx" />
    </Carousel.IndicatorGroup>
    <Carousel.ItemGroup>
      <Carousel.Item v-for="(image, idx) in images" :key="idx" :index="idx">
        <img :src="image" alt="" />
      </Carousel.Item>
    </Carousel.ItemGroup>
  </Carousel.Root>
</template>

// examples/react/src/carousel/autoplay.tsx
import { Carousel } from "@ark-ui/react/carousel";
import { minimal, park, shadcn } from "@spark-css/themes";
import { clsx } from "clsx";
import { type Theme, getTheme } from "../utils";

const images = Array.from({ length: 5 }, (_, i) => `https://picsum.photos/seed/${i + 1}/500/300`);

export const Autoplay = ({ theme }: { theme: Theme }) => {
  const styledSlots = getTheme(
    { minimal: minimal.carousel, park: park.carousel, shadcn: shadcn.carousel },
    theme
  );

  return (
    <Carousel.Root autoplay loop className={clsx(styledSlots.root)}>
      <Carousel.Control className={clsx(styledSlots.control)}>
        <Carousel.AutoplayTrigger className={clsx(styledSlots.autoplayTrigger)}>
          <Carousel.Context>{({ isPlaying }) => (isPlaying ? "Pause" : "Play")}</Carousel.Context>
        </Carousel.AutoplayTrigger>
      </Carousel.Control>
      <Carousel.IndicatorGroup className={clsx(styledSlots.indicatorGroup)}>
        {images.map((_, index) => (
          <Carousel.Indicator key={index} index={index} className={clsx(styledSlots.indicator)} />
        ))}
      </Carousel.IndicatorGroup>
      <Carousel.ItemGroup className={clsx(styledSlots.itemGroup)}>
        {images.map((image, index) => (
          <Carousel.Item key={index} index={index} className={clsx(styledSlots.item)}>
            <img src={image} alt={`Slide ${index}`} />
          </Carousel.Item>
        ))}
      </Carousel.ItemGroup>
    </Carousel.Root>
  );
};
